<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIoUBx4u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIoUBx4u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIoUBx4u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIoUBx4u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIoUBx4u\App_KernelDevDebugContainer([
    'container.build_hash' => 'IoUBx4u',
    'container.build_id' => '4b500bc1',
    'container.build_time' => 1604573484,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIoUBx4u');
